//! Every Zendesk API operation this crate knows, as data.
//!
//! `catalog.json` is generated by `scripts/gen_catalog.py` from Zendesk's OpenAPI specs
//! and its public Postman workspace; do not edit it by hand. The CLI builds its command
//! tree from it and the MCP server searches and calls it.

use std::sync::OnceLock;

use anyhow::{Result, anyhow, bail};
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::ZendeskClient;
use crate::client::segment;

/// One API operation: an HTTP method on a path template such as
/// `/api/v2/tickets/{ticket_id}`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Operation {
    /// Unique, case-insensitively: the OpenAPI `operationId`, e.g. `ShowTicket`.
    pub id: String,
    /// The resource the operation belongs to, e.g. `Tickets`.
    pub group: String,
    pub method: String,
    pub path: String,
    pub summary: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
    /// Path and query parameters.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub params: Vec<Param>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub body: Option<Body>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Param {
    pub name: String,
    #[serde(rename = "in")]
    pub location: Location,
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub required: bool,
    /// The JSON schema type: `string`, `integer`, `boolean`, `array`, `object`, ...
    #[serde(default, rename = "type", skip_serializing_if = "String::is_empty")]
    pub kind: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
    /// The allowed values, when the spec lists them.
    #[serde(default, rename = "enum", skip_serializing_if = "Vec::is_empty")]
    pub values: Vec<String>,
    /// Send an array as repeated `name=value` pairs rather than comma-separated.
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub explode: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Location {
    Path,
    Query,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Body {
    #[serde(default, skip_serializing_if = "std::ops::Not::not")]
    pub required: bool,
    #[serde(default = "json_content_type")]
    pub content_type: String,
    /// An example request body from the spec.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub example: Option<Value>,
}

fn json_content_type() -> String {
    "application/json".into()
}

/// Every operation, in catalog order (grouped by resource).
pub fn operations() -> &'static [Operation] {
    static OPERATIONS: OnceLock<Vec<Operation>> = OnceLock::new();
    OPERATIONS.get_or_init(|| {
        serde_json::from_str(include_str!("catalog.json")).expect("catalog.json is valid")
    })
}

/// The operation with this id, compared case-insensitively.
pub fn find(id: &str) -> Option<&'static Operation> {
    operations()
        .iter()
        .find(|op| op.id.eq_ignore_ascii_case(id))
}

/// Operations matching every word of `query` (case-insensitive substrings of the id,
/// summary, group, path or description), best match first. None for an empty query.
pub fn search(query: &str) -> Vec<&'static Operation> {
    let words: Vec<String> = query.split_whitespace().map(str::to_lowercase).collect();
    if words.is_empty() {
        return Vec::new();
    }
    let mut hits: Vec<(u32, &Operation)> = operations()
        .iter()
        .filter_map(|op| {
            let fields = [
                (op.id.to_lowercase(), 4),
                (op.summary.to_lowercase(), 3),
                (op.group.to_lowercase(), 2),
                (op.path.to_lowercase(), 1),
                (op.description.to_lowercase(), 0),
            ];
            let mut score = 0;
            for word in &words {
                let weights = fields
                    .iter()
                    .filter(|(text, _)| text.contains(word.as_str()));
                score += weights.map(|(_, w)| w).max()?;
            }
            Some((score, op))
        })
        .collect();
    // The shorter of two equal ids is the closer match; stable, so ties keep catalog order.
    hits.sort_by(|a, b| b.0.cmp(&a.0).then(a.1.id.len().cmp(&b.1.id.len())));
    hits.into_iter().map(|(_, op)| op).collect()
}

impl Operation {
    pub fn method(&self) -> reqwest::Method {
        reqwest::Method::from_bytes(self.method.as_bytes()).unwrap_or(reqwest::Method::GET)
    }

    /// Whether the operation only reads.
    pub fn is_read(&self) -> bool {
        self.method == "GET"
    }

    /// The path with `args` filled in (each value percent-encoded as one segment) and the
    /// query string from the remaining `args`. Null values are skipped; an array is sent
    /// comma-separated, or as repeated pairs when the name ends in `[]` or the parameter is
    /// `explode`; an object is sent as `name[key]=value` pairs, so `{"page": {"size": 10}}`
    /// becomes `page[size]=10`.
    pub fn request(&self, args: &Map<String, Value>) -> Result<(String, Vec<(String, String)>)> {
        let mut path = String::new();
        let mut used = Vec::new();
        let mut rest = self.path.as_str();
        while let Some(start) = rest.find('{') {
            let end = rest[start..]
                .find('}')
                .map(|e| start + e)
                .ok_or_else(|| anyhow!("unclosed '{{' in path {}", self.path))?;
            let name = &rest[start + 1..end];
            let value = args
                .get(name)
                .filter(|v| !v.is_null())
                .ok_or_else(|| anyhow!("{} needs the path parameter '{name}'", self.id))?;
            path.push_str(&rest[..start]);
            path.push_str(&segment(&scalar(name, value)?)?);
            used.push(name);
            rest = &rest[end + 1..];
        }
        path.push_str(rest);

        let mut query = Vec::new();
        for (name, value) in args {
            if !used.contains(&name.as_str()) {
                let explode = self.params.iter().any(|p| p.name == *name && p.explode);
                push_query(&mut query, name, value, explode)?;
            }
        }
        if let Some(missing) = self.params.iter().find(|p| {
            p.location == Location::Query
                && p.required
                && args.get(&p.name).is_none_or(Value::is_null)
        }) {
            bail!("{} needs the query parameter '{}'", self.id, missing.name);
        }
        Ok((path, query))
    }
}

/// A string, number or boolean as text.
fn scalar(name: &str, value: &Value) -> Result<String> {
    match value {
        Value::String(s) => Ok(s.clone()),
        Value::Number(_) | Value::Bool(_) => Ok(value.to_string()),
        _ => bail!("'{name}' must be a string, number or boolean"),
    }
}

fn push_query(
    query: &mut Vec<(String, String)>,
    name: &str,
    value: &Value,
    explode: bool,
) -> Result<()> {
    match value {
        Value::Null => {}
        Value::Array(items) if explode || name.ends_with("[]") => {
            for item in items {
                query.push((name.to_string(), scalar(name, item)?));
            }
        }
        Value::Array(items) => {
            let joined: Result<Vec<String>> = items.iter().map(|i| scalar(name, i)).collect();
            query.push((name.to_string(), joined?.join(",")));
        }
        Value::Object(fields) => {
            for (key, value) in fields {
                push_query(query, &format!("{name}[{key}]"), value, false)?;
            }
        }
        _ => query.push((name.to_string(), scalar(name, value)?)),
    }
    Ok(())
}

impl ZendeskClient {
    /// Call a catalog operation. `args` fill the path parameters and the rest become query
    /// parameters (see [`Operation::request`]); `body` is sent as JSON. Returns the JSON
    /// response, `Null` for an empty body.
    pub async fn call_operation(
        &self,
        op: &Operation,
        args: &Map<String, Value>,
        body: Option<&Value>,
    ) -> Result<Value> {
        if let Some(spec) = &op.body {
            if spec.content_type != "application/json" {
                bail!(
                    "{} takes a {} body, which is not supported",
                    op.id,
                    spec.content_type
                );
            }
            if spec.required && body.is_none() {
                bail!("{} needs a request body", op.id);
            }
        }
        let (path, query) = op.request(args)?;
        // `api` takes paths under /api/v2; anything else (ZIS, Jira, ...) goes by URL.
        let target = if path.starts_with("/api/v2/") {
            path
        } else {
            format!("{}{path}", self.origin())
        };
        self.api(op.method(), &target, &query, body).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::Auth;
    use serde_json::json;
    use wiremock::matchers::{body_json, method, path, query_param};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    fn op(value: Value) -> Operation {
        serde_json::from_value(value).unwrap()
    }

    fn args(value: Value) -> Map<String, Value> {
        value.as_object().unwrap().clone()
    }

    fn client(server: &MockServer) -> ZendeskClient {
        ZendeskClient::with_base_url(
            "acme",
            Auth::bearer("t"),
            reqwest::Client::new(),
            format!("{}/api/v2", server.uri()),
        )
    }

    #[test]
    fn catalog_ids_and_paths_have_a_safe_shape() {
        for op in operations() {
            let id_ok = op.id.starts_with(|c: char| c.is_ascii_alphabetic())
                && op.id.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
            assert!(id_ok, "bad id {}", op.id);
            let path_ok = op.path.starts_with('/')
                && !op.path.contains("//")
                && !op.path.contains("..")
                && op
                    .path
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || "._~-/{}".contains(c));
            assert!(path_ok, "bad path {} for {}", op.path, op.id);
        }
    }

    #[test]
    fn catalog_ids_are_unique_and_paths_match_their_params() {
        let ops = operations();
        assert!(!ops.is_empty());
        let mut ids = std::collections::HashSet::new();
        for op in ops {
            assert!(ids.insert(op.id.to_lowercase()), "duplicate id {}", op.id);
            assert!(
                ["GET", "POST", "PUT", "PATCH", "DELETE"].contains(&op.method.as_str()),
                "{}: {}",
                op.id,
                op.method
            );
            assert!(op.path.starts_with('/'), "{}: {}", op.id, op.path);
            assert!(!op.group.is_empty() && !op.summary.is_empty(), "{}", op.id);
            let mut names = std::collections::HashSet::new();
            for p in &op.params {
                assert!(
                    names.insert(&p.name),
                    "{}: duplicate param {}",
                    op.id,
                    p.name
                );
            }
            let in_path: Vec<&str> = op
                .path
                .split('{')
                .skip(1)
                .filter_map(|s| s.split_once('}').map(|(name, _)| name))
                .collect();
            let declared: Vec<&str> = op
                .params
                .iter()
                .filter(|p| p.location == Location::Path)
                .map(|p| p.name.as_str())
                .collect();
            let (mut a, mut b) = (in_path.clone(), declared.clone());
            a.sort();
            b.sort();
            assert_eq!(a, b, "{}: path params", op.id);
            if let Some(body) = &op.body {
                assert!(!body.content_type.is_empty(), "{}", op.id);
            }
        }
    }

    #[test]
    fn find_ignores_case_and_search_ranks_the_id_first() {
        assert_eq!(find("showticket").unwrap().id, "ShowTicket");
        assert!(find("NoSuchOperation").is_none());
        let hits = search("show ticket");
        assert_eq!(hits[0].id, "ShowTicket");
        assert!(hits.iter().all(|op| {
            let text = format!(
                "{} {} {} {} {}",
                op.id, op.summary, op.group, op.path, op.description
            )
            .to_lowercase();
            text.contains("show") && text.contains("ticket")
        }));
        assert!(search("zzzz-nothing").is_empty());
        assert!(search("  ").is_empty());
    }

    #[test]
    fn request_encodes_path_params_and_builds_the_query() {
        let o = op(json!({
            "id": "X", "group": "G", "method": "GET", "summary": "s",
            "path": "/api/v2/things/{thing_id}/parts/{part}",
            "params": [
                {"name": "thing_id", "in": "path", "required": true},
                {"name": "part", "in": "path", "required": true},
                {"name": "at", "in": "query", "explode": true},
            ],
        }));
        let (p, q) = o
            .request(&args(json!({
                "thing_id": 7, "part": "a/b", "ids": [1, 2], "ids[]": [3, 4],
                "page": {"size": 10, "after": "c"}, "flag": true, "skip": null,
                "at": ["x", "y"],
            })))
            .unwrap();
        assert_eq!(p, "/api/v2/things/7/parts/a%2Fb");
        let mut q = q;
        q.sort();
        let expected: Vec<(String, String)> = [
            ("at", "x"),
            ("at", "y"),
            ("flag", "true"),
            ("ids", "1,2"),
            ("ids[]", "3"),
            ("ids[]", "4"),
            ("page[after]", "c"),
            ("page[size]", "10"),
        ]
        .iter()
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect();
        assert_eq!(q, expected);
    }

    #[test]
    fn request_rejects_missing_and_unsafe_params() {
        let o = op(json!({
            "id": "X", "group": "G", "method": "GET", "summary": "s",
            "path": "/api/v2/things/{thing_id}",
            "params": [
                {"name": "thing_id", "in": "path", "required": true},
                {"name": "query", "in": "query", "required": true},
            ],
        }));
        let err = o.request(&args(json!({"query": "x"}))).unwrap_err();
        assert!(err.to_string().contains("'thing_id'"), "{err}");
        let err = o.request(&args(json!({"thing_id": 1}))).unwrap_err();
        assert!(err.to_string().contains("'query'"), "{err}");
        assert!(
            o.request(&args(json!({"thing_id": "..", "query": "x"})))
                .is_err()
        );
        assert!(
            o.request(&args(json!({"thing_id": {"a": 1}, "query": "x"})))
                .is_err()
        );
    }

    #[tokio::test]
    async fn call_operation_sends_the_body_and_reaches_paths_outside_api_v2() {
        let server = MockServer::start().await;
        Mock::given(method("PUT"))
            .and(path("/api/v2/things/7"))
            .and(query_param("include", "users"))
            .and(body_json(json!({"thing": {"name": "n"}})))
            .respond_with(ResponseTemplate::new(200).set_body_json(json!({"ok": 1})))
            .expect(1)
            .mount(&server)
            .await;
        Mock::given(method("GET"))
            .and(path("/api/services/jira/links/5"))
            .respond_with(ResponseTemplate::new(200).set_body_json(json!({"link": {}})))
            .expect(1)
            .mount(&server)
            .await;
        let c = client(&server);
        let put = op(json!({
            "id": "UpdateThing", "group": "G", "method": "PUT", "summary": "s",
            "path": "/api/v2/things/{thing_id}",
            "params": [{"name": "thing_id", "in": "path", "required": true}],
            "body": {"required": true},
        }));
        let got = c
            .call_operation(
                &put,
                &args(json!({"thing_id": 7, "include": "users"})),
                Some(&json!({"thing": {"name": "n"}})),
            )
            .await
            .unwrap();
        assert_eq!(got, json!({"ok": 1}));
        let err = c
            .call_operation(&put, &args(json!({"thing_id": 7})), None)
            .await
            .unwrap_err();
        assert!(err.to_string().contains("needs a request body"), "{err}");

        let jira = op(json!({
            "id": "ShowLink", "group": "G", "method": "GET", "summary": "s",
            "path": "/api/services/jira/links/{link_id}",
            "params": [{"name": "link_id", "in": "path", "required": true}],
        }));
        let got = c
            .call_operation(&jira, &args(json!({"link_id": 5})), None)
            .await
            .unwrap();
        assert_eq!(got, json!({"link": {}}));
    }

    #[tokio::test]
    async fn call_operation_refuses_bodies_it_cannot_send() {
        let server = MockServer::start().await;
        let upload = op(json!({
            "id": "Upload", "group": "G", "method": "POST", "summary": "s",
            "path": "/api/v2/logo",
            "body": {"required": true, "content_type": "multipart/form-data"},
        }));
        let err = client(&server)
            .call_operation(&upload, &Map::new(), Some(&json!({})))
            .await
            .unwrap_err();
        assert!(err.to_string().contains("multipart/form-data"), "{err}");
        assert!(server.received_requests().await.unwrap().is_empty());
    }

    #[test]
    fn paths_outside_api_v2_go_to_the_account_host() {
        let c = ZendeskClient::new("acme", Auth::bearer("t"), reqwest::Client::new());
        assert_eq!(c.origin(), "https://acme.zendesk.com");
    }
}
